### PR TITLE
Dodalem link do firmware drukarki

### PR DESCRIPTION
**Pull request by ritave**

### CODE REVIEW

**Comment by ritave** [comment]
So how about the link from your comment? It helps a lot, couldn't find a link to it on zmorph site.

**Comment by mdebski** [comment]
Shame on you then :P Downloads -> Firmware -> OPEN SOURCE
If you insist, then fine, but change "firmware" to "źródła firmware'u" or sth like that plz.

**Comment by ritave** [comment]
Ping

**Comment by mdebski** [comment]
Pong. See the previous comment: "If you insist, then fine, but change "firmware" to "źródła firmware'u" or sth like that plz."

**Pull request merged**
